# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'presentSenseApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for presentSenseApp
    # Required by RNFirebase
  pod 'Firebase/Core', '~> 5.0.1'
  # [OPTIONAL PODS] - comment out pods for firebase products you won't be using.
  # pod 'Firebase/AdMob'
  pod 'Firebase/Auth'
  # pod 'Firebase/Database'
  # pod 'Firebase/DynamicLinks'
  # pod 'Firebase/Performance'
  pod 'Firebase/Firestore'
  # pod 'Firebase/Messaging'
  # pod 'Firebase/RemoteConfig'
  # pod 'Firebase/Storage'

  pod 'Fabric', '~> 1.7.6'
  pod 'Crashlytics', '~> 3.10.1'
  # pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  #Google Maps
  pod 'Google-Maps-iOS-Utils', :git => 'https://github.com/pjamrozowicz/google-maps-ios-utils.git'

  target 'presentSenseApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    # pod 'react-native-webgl', :path => '../node_modules/react-native-webgl'


  end

  target 'presentSenseAppTests' do
    inherit! :search_paths
    # Pods for testing
  end


end

# target 'presentSenseApp-tvOS' do
#   # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
#   # use_frameworks!

#   # Pods for presentSenseApp-tvOS

#   # target 'presentSenseApp-tvOSTests' do
#   #   inherit! :search_paths
#     # Pods for testing
#   # end

# end
